


WITH CTE1 AS (

SELECT ID,customer,STL_BEZ,DEFF_1 ,lmn_1
FROM 
(
	SELECT *,ROW_NUMBER() OVER (PARTITION BY ID,BOM_NODE,BOM_LEVEL ORDER BY BOM_ID)  AS rn_1
			,ROW_NUMBER() OVER (PARTITION BY ID,STL_BIT,STL_PRODART,STL_PRODGRP ORDER BY BOM_ID) AS rn_2
			,CASE WHEN STL_BEZ LIKE 'LAMÝNE 2 KAT' THEN 1 ELSE 0 END AS lmn_1
	FROM
			(SELECT *,
				CASE WHEN SUBSTRING(ID,1,1)=1 THEN 'MONOLITHIC_GLASS'
					WHEN SUBSTRING(ID,1,1)=2 THEN CASE WHEN SUBSTRING(ID,2,1)=8 THEN  'TRIPLE_IG_UNIT' ELSE 'IG_UNIT' END
					WHEN SUBSTRING(ID,1,1)=5 THEN 'MONOLITHIC_GLASS_WITH_PROCESES'
					WHEN SUBSTRING(ID,1,1)=7 THEN 'LAMI_GLASS'
					WHEN SUBSTRING(ID,1,1)=3 AND LEN(ID)=7 THEN 'SAMPLE'
					ELSE 'TEST'
					END AS DEFF_1
		FROM
			(SELECT  Q1.ID,
					Q1.STATUS,
					Q1.customer,
					BOM_ID,
					BOM_NODE,
					STL_BIT,
					STL_PRODART,
					STL_PRODGRP,
					STL_BEZ,
					POS_NR,
					BOM_LEVEL
			FROM
			(
				SELECT CAST(ID AS CHAR) AS ID,
				STATUS,
				AH_NAME1+AH_NAME2 as customer
				FROM [SYSADM].[BW_AUFTR_KOPF]
				WHERE DATUM_LIEFER_TAT>'2020-01-01'
				AND DATUM_ERF>'2020-01-01'
				AND DATUM_PROD1<GETDATE()
				AND STATUS NOT IN (596,900) 
				AND STATUS>450
				AND LEN(ID)>=5
				AND ID NOT IN ( SELECT ID FROM [SYSADM].[BW_AUFTR_KOPF] WHERE LEN(ID)>6 AND SUBSTRING(CONVERT(char,ID),1,1) IN (1,2,4,5,6,7,8,9))
				AND SUBSTRING(CONVERT(char,ID),1,1)<>9
			
			) AS Q1
			LEFT JOIN [SYSADM].[BW_AUFTR_STKL] STK ON Q1.ID=STK.ID
			WHERE POS_NR=1

		
			) AS Q2
		) AS Q3
	--WHERE Q3.ID=213629
) AS Q4
WHERE  
STL_BIT=12
AND
STL_PRODART=2

)
,CTE2 AS (SELECT ID,SUM(CTE1.lmn_1) AS q_lmn
	FROM CTE1 
	GROUP BY ID)

SELECT C2.ID,C1.customer,C1.STL_BEZ,OD.NEWDEFF FROM CTE2 C2 JOIN CTE1 C1 ON C2.ID=C1.ID
			LEFT JOIN ARDMAIN.dbo.DG_ORDERDETAIL OD ON C2.ID=OD.ORDER_NUMBER

